export const SIGN_UP_REDUCER = 'SIGN_UP_REDUCER';
export const SIGN_IN_REDUCER = 'SIGN_IN_REDUCER';
export const LOGOUT_REDUCER = 'LOGOUT_REDUCER';

export const SIGN_UP_SAGA = 'SIGN_UP_SAGA';
export const SIGN_IN_SAGA = 'SIGN_IN_SAGA';
export const LOGOUT_SAGA = 'LOGOUT_SAGA';
export const SAVE_TOKEN_SAGA = 'SAVE_TOKEN_SAGA';

export const FORGOT_PASSWORD_SAGA = 'FORGOT_PASSWORD_SAGA';
export const FORGOT_PASSWORD_CONFIRM_SAGA = 'FORGOT_PASSWORD_CONFIRM_SAGA';
