export const GET_PROJECTS_LIST_SAGA = 'GET_PROJECTS_LIST_SAGA';
export const CREATE_PROJECT_SAGA = 'CREATE_PROJECT_SAGA';
export const UPDATE_PROJECT_SAGA = 'UPDATE_PROJECT_SAGA';
export const DELETE_PROJECT_SAGA = 'DELETE_PROJECT_SAGA';

export const GET_PROJECTS_LIST_REDUCER = 'GET_PROJECTS_LIST_REDUCER';
export const CREATE_PROJECT_REDUCER = 'CREATE_PROJECT_REDUCER';
export const UPDATE_PROJECT_REDUCER = 'UPDATE_PROJECT_REDUCER';
export const DELETE_PROJECT_REDUCER = 'DELETE_PROJECT_REDUCER';