export const GET_TASKS_DATA_SAGA = 'GET_TASKS_DATA_SAGA';
export const CREATE_TASK_SAGA = 'CREATE_TASK_SAGA';
export const UPDATE_TASK_SAGA = 'UPDATE_TASK_SAGA';
export const UPDATE_TASK_STATUS_SAGA = 'UPDATE_TASK_STATUS_SAGA';
export const DELETE_TASK_SAGA = 'DELETE_TASK_SAGA';


export const GET_TASKS_DATA_REDUCER = 'GET_TASKS_DATA_REDUCER';
export const CREATE_TASK_REDUCER = 'CREATE_TASK_REDUCER';
export const UPDATE_TASK_REDUCER = 'UPDATE_TASK_REDUCER';
export const UPDATE_TASK_STATUS_REDUCER = 'UPDATE_TASK_STATUS_REDUCER';
export const DELETE_TASK_REDUCER = 'DELETE_TASK_REDUCER';