export const GET_USERS_SAGA = 'GET_USERS_SAGA';
export const UPDATE_USER_ROLE_SAGA = 'UPDATE_USER_ROLE_SAGA';
export const GET_USERS_ROLES_SAGA = 'GET_USERS_ROLES_SAGA';
export const UPLOAD_NEW_USER_SAGA = 'UPLOAD_NEW_USER_SAGA';

export const RESET_PASSWORD_SAGA = 'RESET_PASSWORD_SAGA';

export const GET_USERS_REDUCER = 'GET_USERS_REDUCER';
export const UPDATE_USER_ROLE_REDUCER = 'UPDATE_USER_ROLE_REDUCER';
export const GET_USERS_ROLES_REDUCER = 'GET_USERS_ROLES_REDUCER';
export const UPLOAD_NEW_USER_REDUCER = 'UPLOAD_NEW_USER_REDUCER';
export const UPDATE_LOGGED_USER_REDUCER = 'UPDATE_LOGGED_USER_REDUCER';